### ISSUE TITLE
Future work

### ISSUE THREAD

**Issue by cankisagun** [baedrik/SCRT-sealed-bid-auction#4]
Next steps for secretAuction are:

1) Add a factory contract:
This will allow the UI to keep track of open auctions very easily, rather than scanning the entire blockchain for all auctions.

2) Change min_bid price w/o closing the auction

3) Variable price bids:
We need to find a way to make sure that min. prices doesn't stay out of the money. This creates a poor experience to only see auctions where you don't want to participate. The idea would be to first add variable price bids for the seller. I would create an auction and say I'm selling at marketprice, -1% below market price, +1% market price. The lowest bid can be updated periodically (every 100 blocks etc.)
_This also requires an oracle integration (see https://github.com/enigmampc/SecretNetwork/issues/697)_

4) Auctions with a closing time (issue #5)

5) Seller anonymity (lowest priority)

**Comment by cankisagun** [comment]
Factory contract is complete

**Comment by baedrik** [comment]
Closing times and manually changing min bid are complete
